# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - web-containers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c177b209f6e34f9ab43fed0c4827f12d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aa939884b48e40149566913e840c052e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c177b209f6e34f9ab43fed0c4827f12d }}/abeskik/webapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'web-containers'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6f9a6ac7b96545408eb9c7e5de79ac21 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c177b209f6e34f9ab43fed0c4827f12d }}/abeskik/webapp:${{ github.sha }}'